---
- hosts: localhost
  connection: local  # Run tasks locally without SSH
  become: yes
  vars:
    aws_region: "eu-central-1"  # Preferred AWS region

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Print AWS Region
      debug:
        msg: "AWS region is set to: {{ aws_region }}"

    - name: Login to Amazon ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin 605134428871.dkr.ecr.{{ aws_region }}.amazonaws.com
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        AWS_DEFAULT_REGION: "{{ aws_region }}"
      args:
        executable: /bin/bash

    - name: Pull FastAPI Docker image
      docker_image:
        name: 605134428871.dkr.ecr.{{ aws_region }}.amazonaws.com/your-desired-repo-name:latest
        source: pull

    - name: Run FastAPI container
      docker_container:
        name: fastapi-app
        image: 605134428871.dkr.ecr.{{ aws_region }}.amazonaws.com/your-desired-repo-name:latest
        state: started
        ports:
          - "80:80"
